### ISSUE TITLE
`lintpkg` broken

### ISSUE THREAD

**Issue by TotalVerb** [tonyhffong/Lint.jl#136]
Doesn't actually print anything. Only returns stuff when keyword argument is set.

**Comment by Michael-Klassen** [comment]
If `lintpkg` doesn't print anything that means `Lint` didn't find any problems. I think the reason why returning nothing is the default is because it looks cleaner when run in the REPL. That being said I agree that when you want to do additional processing on the output then having to add the keyword argument can be annoying.
